In [1]:
'''
Neuron: Takes input signal(s), gives an output signal(s).

Activation Function: Value that is passed as output.
    * Threshold function (0 or 1)
    * Sigmoid function
    * Rectifier (zero until a point then activatives)
    * Hyperbolic Tangent (-1 to +1)


Input Layer: The inputs into the network.

Hidden Layer: Layers inbetween input/output to influence outputs.

Output Layer: Answers/Predicitons

Weights: Each neuron has a weight to its output.

Cost Function: Difference between result and desired result.

Backward Propergation: Difference between output and desired output and 
    feed difference back into network for weights to be adjusted.
    
Gradient Descent: Find the global minimum of the network.
    Think of a x^2 on a graph and finding the lowest point on y-axis.

Stochastic Gradient Descent: Find global minimum but avoid finding the local.
    minimum as there might be a lower point else where.

'''

'\nNeuron: Takes input signal(s), gives an output signal(s).\n\nActivation Function: Value that is passed as output.\n    * Threshold function (0 or 1)\n    * Sigmoid function\n    * Rectifier (zero until a point then activatives)\n    * Hyperbolic Tangent (-1 to +1)\n\n\nInput Layer: The inputs into the network.\n\nHidden Layer: Layers inbetween input/output to influence outputs.\n\nOutput Layer: Answers/Predicitons\n\nWeights: Each neuron has a weight to its output.\n\nCost Function: Difference between result and desired result.\n\nBackward Propergation: Difference between output and desired output and \n    feed difference back into network for weights to be adjusted.\n    \nGradient Descent: Find the global minimum of the network.\n    Think of a x^2 on a graph and finding the lowest point on y-axis.\n\nStochastic Gradient Descent: Find global minimum but avoid finding the local.\n    minimum as there might be a lower point else where.\n\n'

In [13]:
# Import librarys
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import confusion_matrix

In [3]:
# Import the dataset
'''
Bank customers dataset. Why people are leaving the Bank for other Banks.
'''

root = '/Users/Haydn/Documents/Code/Jupyter/Machine Learning A-Z/1.0 - Example Data/Part 8 - Deep Learning/'
data_file = root + 'Artificial Neural Networks (ANN)/Churn_Modelling.csv'
dataset = pd.read_csv(data_file)
dataset

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0
12,13,15632264,Kay,476,France,Female,34,10,0.00,2,1,0,26260.98,0
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0
14,15,15600882,Scott,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
17,18,15788218,Henderson,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0
18,19,15661507,Muldrow,587,Spain,Male,45,6,0.00,1,0,0,158684.81,0
19,20,15568982,Hao,726,France,Female,24,6,0.00,2,1,1,54724.03,0
20,21,15577657,McDonald,732,France,Male,41,8,0.00,2,1,1,170886.17,0
21,22,15597945,Dellucci,636,Spain,Female,32,8,0.00,2,1,0,138555.46,0
22,23,15699309,Gerasimov,510,Spain,Female,38,4,0.00,1,1,0,118913.53,1
23,24,15725737,Mosman,669,France,Male,46,3,0.00,2,0,1,8487.75,0
24,25,15625047,Yen,846,France,Female,38,5,0.00,1,1,1,187616.16,0
25,26,15738191,Maclean,577,France,Male,25,3,0.00,2,0,1,124508.29,0
26,27,15736816,Young,756,Germany,Male,36,2,136815.64,1,1,1,170041.95,0
27,28,15700772,Nebechi,571,France,Male,44,9,0.00,2,0,0,38433.35,0
28,29,15728693,McWilliams,574,Germany,Female,43,3,141349.43,1,1,1,100187.43,0
29,30,15656300,Lucciano,411,France,Male,29,0,59697.17,2,1,1,53483.21,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,9971,15587133,Thompson,518,France,Male,42,7,151027.05,2,1,0,119377.36,0
9971,9972,15721377,Chou,833,France,Female,34,3,144751.81,1,0,0,166472.81,0
9972,9973,15747927,Ch'in,758,France,Male,26,4,155739.76,1,1,0,171552.02,0
9973,9974,15806455,Miller,611,France,Male,27,7,0.00,2,1,1,157474.10,0
9974,9975,15695474,Barker,583,France,Male,33,7,122531.86,1,1,0,13549.24,0
9975,9976,15666295,Smith,610,Germany,Male,50,1,113957.01,2,1,0,196526.55,1
9976,9977,15656062,Azikiwe,637,France,Female,33,7,103377.81,1,1,0,84419.78,0
9977,9978,15579969,Mancini,683,France,Female,32,9,0.00,2,1,1,24991.92,0
9978,9979,15703563,P'eng,774,France,Male,40,9,93017.47,2,1,0,191608.97,0
9979,9980,15692664,Diribe,677,France,Female,58,1,90022.85,1,0,1,2988.28,0
9980,9981,15719276,T'ao,741,Spain,Male,35,6,74371.49,1,0,0,99595.67,0
9981,9982,15672754,Burbidge,498,Germany,Male,42,3,152039.70,1,1,1,53445.17,1
9982,9983,15768163,Griffin,655,Germany,Female,46,7,137145.12,1,1,0,115146.40,1
9983,9984,15656710,Cocci,613,France,Male,40,4,0.00,1,0,0,151325.24,0
9984,9985,15696175,Echezonachukwu,602,Germany,Male,35,7,90602.42,2,1,1,51695.41,0
9985,9986,15586914,Nepean,659,France,Male,36,6,123841.49,2,1,0,96833.00,0
9986,9987,15581736,Bartlett,673,Germany,Male,47,1,183579.54,2,0,1,34047.54,0
9987,9988,15588839,Mancini,606,Spain,Male,30,8,180307.73,2,1,1,1914.41,0
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
# Features and outcomes
x = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
x, y

(array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
        [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
        [502, 'France', 'Female', ..., 1, 0, 113931.57],
        ...,
        [709, 'France', 'Female', ..., 0, 1, 42085.58],
        [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
        [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object),
 array([1, 0, 1, ..., 1, 1, 0]))

In [5]:
# Encode the categorical data
label_encoder_1 = LabelEncoder()
label_encoder_2 = LabelEncoder()
x[:, 1] = label_encoder_1.fit_transform(x[:, 1]) # Country
x[:, 2] = label_encoder_2.fit_transform(x[:, 2]) # Gender

transformer_1 = ColumnTransformer([("country", OneHotEncoder(categories='auto'), [1])])
country_data = transformer_1.fit_transform(x)
transformer_2 = ColumnTransformer([("gender", OneHotEncoder(categories='auto'), [2])])
gender_data = transformer_2.fit_transform(x)

credit_score = x[:, [0]]
categorical_data = np.concatenate((country_data, gender_data), axis=1)
x = np.concatenate((credit_score, categorical_data, x[:, 3:]), axis=1)
x

array([[619, 1.0, 0.0, ..., 1, 1, 101348.88],
       [608, 0.0, 0.0, ..., 0, 1, 112542.58],
       [502, 1.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [709, 1.0, 0.0, ..., 0, 1, 42085.58],
       [772, 0.0, 1.0, ..., 1, 0, 92888.52],
       [792, 1.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [6]:
# Split test and train data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0)

In [7]:
# Feature Scaling
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train

array([[ 0.16958176, -1.01460667, -0.5698444 , ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-2.30455945, -1.01460667,  1.75486502, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-1.19119591,  0.98560362, -0.5698444 , ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.9015152 ,  0.98560362, -0.5698444 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.62420521, -1.01460667, -0.5698444 , ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-0.28401079, -1.01460667,  1.75486502, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [8]:
# Make the ANN
model = Sequential()

In [9]:
# Adding some input and hiddern layers
# help(Dense)

# Layer 1
model.add(
    Dense(
        6, # number of neurons
        kernel_initializer='uniform', # random values for initialization
        activation='relu', # activation function
        input_dim=13,
    )
)

# Hidden layer
model.add(
    Dense(
        6, # number of neurons
        kernel_initializer='uniform', # random values for initialization
        activation='relu', # activation function
    )
)

In [10]:
# Output layer
model.add(
    Dense(
        1, # number of neurons
        kernel_initializer='uniform', # random values for initialization
        activation='sigmoid', # activation function
    )
)

In [11]:
# Complie
model.compile(
    optimizer='adam', # how to optimse the netwrok
    loss='binary_crossentropy', # loss function
    metrics=['accuracy'] # what we're interested in
)

In [12]:
# Fitting and training to the training data
model.fit(
    x_train, y_train,
    batch_size=10,
    epochs=100
)

Epoch 1/100
8000/8000 [==============================] - 2s 202us/step - loss: 0.4826 - acc: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.4288 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.4229 - acc: 0.7975
Epoch 4/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.4193 - acc: 0.8224
Epoch 5/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.4165 - acc: 0.8265
Epoch 6/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.4146 - acc: 0.8291
Epoch 7/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.4134 - acc: 0.8315
Epoch 8/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.4123 - acc: 0.8316
Epoch 9/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.4107 - acc: 0.8332
Epoch 10/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.4100 - acc: 0.8349
Epoch 11/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.4092 - acc: 0.8356
Epoch 12/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.4083 - acc: 0.8340
Epoch 13/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.4081 - acc: 0.8346
Epoch 14/100
8000/8000 [==============================] - 1s 168us/step - loss: 0.4076 - acc: 0.8355
Epoch 15/100
8000/8000 [==============================] - 1s 151us/step - loss: 0.4067 - acc: 0.8350
Epoch 16/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.4062 - acc: 0.8361
Epoch 17/100
8000/8000 [==============================] - 1s 150us/step - loss: 0.4063 - acc: 0.8346
Epoch 18/100
8000/8000 [==============================] - 1s 169us/step - loss: 0.4053 - acc: 0.8359
Epoch 19/100
8000/8000 [==============================] - 1s 153us/step - loss: 0.4056 - acc: 0.8357
Epoch 20/100
8000/8000 [==============================] - 1s 169us/step - loss: 0.4051 - acc: 0.8342
Epoch 21/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.4043 - acc: 0.8367
Epoch 22/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.4040 - acc: 0.8341
Epoch 23/100
8000/8000 [==============================] - 1s 149us/step - loss: 0.4038 - acc: 0.8349
Epoch 24/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.4039 - acc: 0.8345
Epoch 25/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.4034 - acc: 0.8339
Epoch 26/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.4034 - acc: 0.8344
Epoch 27/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.4029 - acc: 0.8352
Epoch 28/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.4031 - acc: 0.8332
Epoch 29/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.4033 - acc: 0.8346
Epoch 30/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.4025 - acc: 0.8342
Epoch 31/100
8000/8000 [==============================] - 1s 166us/step - loss: 0.4024 - acc: 0.8337
Epoch 32/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.4020 - acc: 0.8356
Epoch 33/100
8000/8000 [==============================] - 1s 154us/step - loss: 0.4016 - acc: 0.8346
Epoch 34/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.4013 - acc: 0.8359
Epoch 35/100
8000/8000 [==============================] - 1s 158us/step - loss: 0.4006 - acc: 0.8356
Epoch 36/100
8000/8000 [==============================] - 1s 159us/step - loss: 0.3995 - acc: 0.8347
Epoch 37/100
8000/8000 [==============================] - 1s 153us/step - loss: 0.3997 - acc: 0.8366
Epoch 38/100
8000/8000 [==============================] - 1s 153us/step - loss: 0.3997 - acc: 0.8349
Epoch 39/100
8000/8000 [==============================] - 1s 163us/step - loss: 0.3982 - acc: 0.8357
Epoch 40/100
8000/8000 [==============================] - 1s 158us/step - loss: 0.3984 - acc: 0.8376
Epoch 41/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.3981 - acc: 0.8351
Epoch 42/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.3979 - acc: 0.8365
Epoch 43/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.3975 - acc: 0.8355
Epoch 44/100
8000/8000 [==============================] - 1s 159us/step - loss: 0.3973 - acc: 0.8364
Epoch 45/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.3968 - acc: 0.8364
Epoch 46/100
8000/8000 [==============================] - 1s 164us/step - loss: 0.3972 - acc: 0.8357
Epoch 47/100
8000/8000 [==============================] - 1s 158us/step - loss: 0.3965 - acc: 0.8370
Epoch 48/100
8000/8000 [==============================] - 1s 157us/step - loss: 0.3967 - acc: 0.8360
Epoch 49/100
8000/8000 [==============================] - 1s 162us/step - loss: 0.3967 - acc: 0.8364
Epoch 50/100
8000/8000 [==============================] - 1s 162us/step - loss: 0.3958 - acc: 0.8357
Epoch 51/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.3957 - acc: 0.8361
Epoch 52/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.3960 - acc: 0.8365
Epoch 53/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.3956 - acc: 0.8367
Epoch 54/100
8000/8000 [==============================] - 1s 154us/step - loss: 0.3957 - acc: 0.8356
Epoch 55/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.3959 - acc: 0.8366
Epoch 56/100
8000/8000 [==============================] - 1s 166us/step - loss: 0.3955 - acc: 0.8350
Epoch 57/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.3956 - acc: 0.8359
Epoch 58/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.3958 - acc: 0.8376
Epoch 59/100
8000/8000 [==============================] - 1s 172us/step - loss: 0.3954 - acc: 0.8357
Epoch 60/100
8000/8000 [==============================] - 1s 159us/step - loss: 0.3951 - acc: 0.8372
Epoch 61/100
8000/8000 [==============================] - 1s 156us/step - loss: 0.3945 - acc: 0.8374
Epoch 62/100
8000/8000 [==============================] - 1s 163us/step - loss: 0.3950 - acc: 0.8364
Epoch 63/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3952 - acc: 0.8361
Epoch 64/100
8000/8000 [==============================] - 1s 184us/step - loss: 0.3946 - acc: 0.8366
Epoch 65/100
8000/8000 [==============================] - 1s 170us/step - loss: 0.3951 - acc: 0.8379
Epoch 66/100
8000/8000 [==============================] - 1s 172us/step - loss: 0.3947 - acc: 0.8370
Epoch 67/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.3949 - acc: 0.8361
Epoch 68/100
8000/8000 [==============================] - 1s 155us/step - loss: 0.3952 - acc: 0.8350
Epoch 69/100
8000/8000 [==============================] - 1s 159us/step - loss: 0.3946 - acc: 0.8364
Epoch 70/100
8000/8000 [==============================] - 1s 150us/step - loss: 0.3944 - acc: 0.8369
Epoch 71/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.3944 - acc: 0.8375
Epoch 72/100
8000/8000 [==============================] - 1s 160us/step - loss: 0.3947 - acc: 0.8386
Epoch 73/100
8000/8000 [==============================] - 1s 151us/step - loss: 0.3949 - acc: 0.8375
Epoch 74/100
8000/8000 [==============================] - 1s 158us/step - loss: 0.3944 - acc: 0.8379
Epoch 75/100
8000/8000 [==============================] - 1s 151us/step - loss: 0.3936 - acc: 0.8364
Epoch 76/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.3936 - acc: 0.8365
Epoch 77/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3940 - acc: 0.8384
Epoch 78/100
8000/8000 [==============================] - 1s 149us/step - loss: 0.3942 - acc: 0.8370
Epoch 79/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.3937 - acc: 0.8381
Epoch 80/100
8000/8000 [==============================] - 1s 152us/step - loss: 0.3940 - acc: 0.8372
Epoch 81/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.3934 - acc: 0.8367
Epoch 82/100

8000/8000 [==============================] - 1s 147us/step - loss: 0.3941 - acc: 0.8376
Epoch 83/100
8000/8000 [==============================] - 1s 145us/step - loss: 0.3929 - acc: 0.8359
Epoch 84/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.3936 - acc: 0.8372
Epoch 85/100
8000/8000 [==============================] - 1s 141us/step - loss: 0.3935 - acc: 0.8370
Epoch 86/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.3935 - acc: 0.8375
Epoch 87/100
8000/8000 [==============================] - 1s 158us/step - loss: 0.3937 - acc: 0.8381
Epoch 88/100
8000/8000 [==============================] - 1s 161us/step - loss: 0.3934 - acc: 0.8356
Epoch 89/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.3932 - acc: 0.8376
Epoch 90/100
8000/8000 [==============================] - 1s 174us/step - loss: 0.3935 - acc: 0.8366
Epoch 91/100
8000/8000 [==============================] - 1s 178us/step - loss: 0.3931 - acc: 0.8379
Epoch 92/100
8000/8000 [==============================] - 1s 176us/step - loss: 0.3927 - acc: 0.8377
Epoch 93/100
8000/8000 [==============================] - 1s 179us/step - loss: 0.3936 - acc: 0.8357
Epoch 94/100
8000/8000 [==============================] - 2s 193us/step - loss: 0.3933 - acc: 0.8380
Epoch 95/100
8000/8000 [==============================] - 2s 191us/step - loss: 0.3928 - acc: 0.8375
Epoch 96/100
8000/8000 [==============================] - 2s 208us/step - loss: 0.3925 - acc: 0.8377
Epoch 97/100
8000/8000 [==============================] - 2s 204us/step - loss: 0.3930 - acc: 0.8377
Epoch 98/100
8000/8000 [==============================] - 2s 200us/step - loss: 0.3926 - acc: 0.8376
Epoch 99/100
8000/8000 [==============================] - 2s 203us/step - loss: 0.3931 - acc: 0.8387
Epoch 100/100
8000/8000 [==============================] - 2s 201us/step - loss: 0.3928 - acc: 0.8384

In [14]:
# Lets check resutls
y_predictions = model.predict(x_test)
y_predictions = (y_predictions > 0.5) # To get binary of left or stayed at Bank

In [16]:
# Lets see the results
cm = confusion_matrix(y_test, y_predictions)
cm

array([[1545,   50],
       [ 262,  143]])

In [19]:
'Accuracy', ((cm[0][0] + cm[1][1]) / 2000) * 100

('Accuracy', 84.39999999999999)